name = "ReSolverFlowsBase"
uuid = "9778a910-ce4d-423e-92be-12991f0cf10c"
version = "0.1.0"
authors = ["Thomas Burton <tburton5572@gmail.com>"]

[workspace]
projects = ["test", "benchmark"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
FDGrids = "28eb41cd-435a-4ede-8bdb-f2685fc03e8c"
HaloArrays = "fb8acbf3-7450-4a92-9b90-d90d6800475e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extensions]
CUDAExt = ["CUDA", "FDGrids"]
MPIExt = ["MPI", "FDGrids", "HaloArrays"]
MPICUDAExt = ["MPI", "CUDA", "FDGrids", "HaloArrays"]
MPIIntermediateExt = ["MPI", "FDGrids"]

[compat]
Adapt = "4.7.0"
FDGrids = "≥0.3.2"
FFTW = "1.8"
HaloArrays = "0.1, 0.2"
JLD2 = "0.4, 0.5, 0.6"
MPI = "0.20.23"
julia = "1.10"
